server:
  port: 18083
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #nacos 服务地址
    sentinel:
      transport:
        dashboard: localhost:8080   #sentinel 服务地址
        port: 8719
  zipkin:
    base-url: http://localhost:9411  # zipkin 分布式链路追踪  服务地址
    sender:
      type: web     #交互方式
    discovery-client-enabled: false #不追踪自己的请求
  sleuth:
    sampler:
      probability: 1  #sleuth 采集率 1代表百分百
      # mysql数据库和redis数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.80.130:3306/guli_wms
    username: root
    password: 123456
  redis:
    host: 192.168.80.130

feign:
  sentinel:
    enabled: true  #启用feign的 sentinel
#dao层编译后只有class文件，没有mapper.xml，
#因为maven工程在默认情况下src/main/java目录下的所有资源文件是不发布到target目录下的
#解决方法:  让maven默认加载xml文件
# 1.在pom.xml进行配置
# 2.在application.properties进行配置
#配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath:mapper/wms/**/*.xml
  # 类型别名
  type-aliases-package: com.atguigu.gmall.wms.entity
  #全局id策略
  global-config:
    db-config:
      id-type: auto
